### ISSUE TITLE
multiple gsi

### ISSUE THREAD

**Issue by klinquist** [bchew/dynamodump#11]
Amazon now allows for multiple gsis.. I'm thinking that may be the cause of this failure:

python dynamobackup.py -m restore -r us-west-2 -s dev_UserSeeds -d dev_UserSeeds4
INFO:root:dev_UserSeeds4 table deleted!
INFO:root:Starting restore for dev_UserSeeds to dev_UserSeeds4..
INFO:root:Creating dev_UserSeeds4 table with temp write capacity of 100
INFO:root:Waiting for dev_UserSeeds4 table to be created.. [CREATING]
INFO:root:Waiting for dev_UserSeeds4 table to be created.. [CREATING]
INFO:root:dev_UserSeeds4 created.
INFO:root:Restoring data for dev_UserSeeds4 table..
INFO:root:Processing 0001.json of dev_UserSeeds4
Traceback (most recent call last):
  File "dynamobackup.py", line 419, in <module>
    do_restore(conn, sleep_interval, args.srcTable, dest_table, args.writeCapacity)
  File "dynamobackup.py", line 291, in do_restore
    batch_write(conn, sleep_interval, destination_table, put_requests)
  File "dynamobackup.py", line 118, in batch_write
    response = conn.batch_write_item(request_items)
  File "/Library/Python/2.7/site-packages/boto/dynamodb2/layer1.py", line 420, in batch_write_item
    body=json.dumps(params))
  File "/Library/Python/2.7/site-packages/boto/dynamodb2/layer1.py", line 2842, in make_request
    retry_handler=self._retry_handler)
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 953, in _mexe
    status = retry_handler(response, i, next_sleep)
  File "/Library/Python/2.7/site-packages/boto/dynamodb2/layer1.py", line 2882, in _retry_handler
    response.status, response.reason, data)
boto.dynamodb2.exceptions.ValidationException: ValidationException: 400 Bad Request
{u'message': u'One or more parameter values were invalid: Type mismatch for Index Key thingId Expected: S Actual: M IndexName: gsi_UserSeeds_thingId', u'__type': u'com.amazon.coral.validate#ValidationException'}

**Comment by klinquist** [comment]
Nevermind.   I had some junk data in my source table.

I put a try/catch around the batch_write to solve.  Of course, I end up losing any other writes in the MAX_BATCH_WRITE.
