### ISSUE TITLE
LocalSecondaryIndexes 

### ISSUE THREAD

**Issue by onion1984** [bchew/dynamodump#197]
Hi, really nice project, keep it up. 
I just found one issue when I tried to backup and restore a table with LocalSecondaryIndex. It turns out that IndexSizeBytes，ItemCount and IndexArn are not required for creating LocalSecondaryIndex.
Here is the error messages:
[ec2-user@ip-10-0-1-110 dynamodump]$ dynamodump -m restore -r ap-southeast-2 -s demo2 --schemaOnly
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
About to delete table demo2. Type 'yes' to continue: yes
INFO:root:demo2 table deleted!
INFO:root:Starting restore for demo2 to demo2..
INFO:root:Creating demo2 table with temp write capacity of 25
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/dynamodump", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.7/site-packages/dynamodump/dynamodump.py", line 1497, in main
    billing_mode=args.billingMode,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/dynamodump/dynamodump.py", line 924, in do_restore
    **optional_args
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 902, in _make_api_call
    api_params, operation_model, context=request_context
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 963, in _convert_to_request_dict
    api_params, operation_model
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in LocalSecondaryIndexes[0]: "IndexSizeBytes", must be one of: IndexName, KeySchema, Projection
Unknown parameter in LocalSecondaryIndexes[0]: "ItemCount", must be one of: IndexName, KeySchema, Projection
Unknown parameter in LocalSecondaryIndexes[0]: "IndexArn", must be one of: IndexName, KeySchema, Projection

After I removed IndexSizeBytes, ItemCount, IndexArn, it works perfectly fine.

**Comment by DilLip-Chowdary-Codes** [comment]
I too got the same issue

**Comment by DilLip-Chowdary-Codes** [comment]
#198

**Comment by onion1984** [comment]
This issue still exist when i use the tool today
[ec2-user@ip-10-0-1-110 dynamodump]$ dynamodump -m restore -r ap-northeast-1 -s "*" --schemaOnly
INFO:botocore.credentials:Found credentials in environment variables.
INFO:root:Found 0 table(s) in DynamoDB host to be deleted: 
INFO:root:Found 3 table(s) in dump to restore: demo1, demo3, demo2
INFO:root:Starting restore for demo1 to demo1..
INFO:root:Creating demo1 table with temp write capacity of 25
INFO:root:Waiting for demo1 table to be created.. [CREATING]
INFO:root:Starting restore for demo3 to demo3..
INFO:root:Creating demo3 table with temp write capacity of 25
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/dynamodump/dynamodump.py", line 924, in do_restore
    **optional_args
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 902, in _make_api_call
    api_params, operation_model, context=request_context
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/client.py", line 963, in _convert_to_request_dict
    api_params, operation_model
  File "/home/ec2-user/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in LocalSecondaryIndexes[0]: "IndexSizeBytes", must be one of: IndexName, KeySchema, Projection
Unknown parameter in LocalSecondaryIndexes[0]: "ItemCount", must be one of: IndexName, KeySchema, Projection
Unknown parameter in LocalSecondaryIndexes[0]: "IndexArn", must be one of: IndexName, KeySchema, Projection

**Comment by DilLip-Chowdary-Codes** [comment]
Can you share the version you're using?

**Comment by onion1984** [comment]
I am not sure how to check the version. i just downloaded the git repo to my local instance, so I assume it is the latest [1.8.0]version
