### ISSUE TITLE
Feature request: expired token backoff/retry

### ISSUE THREAD

**Issue by rorybakerfmr** [bchew/dynamodump#259]
Hello, I am using dynamodump in an environment where we use session tokens that expire after less than an hour, and can expire before the backup or restoration of a large table is complete. To get around this, I have a script that will refresh my session token and write a new key/secret to `~/.aws/credentials`. However, the operation will still sometimes fail due to the boto client still having the old credentials in memory. To mitigate this, I would like to have a backoff/retry loop that will wait a few seconds and try again after encountering an ExpiredTokenException. 

Feature:
- Backup/restore works on a loop. If an ExpiredTokenException is encountered, sleep a few seconds and try again.
- If non-expired credentials are loaded, then the operation can proceed
- If non-expired credentials are not available after a few tries, bubble up the error to the user and abort

I will try to implement a solution soon and open a pull request, but I wanted to open this issue now in case anyone had a similar issue or knew of a workaround. I've tried refreshing the token before the advertised expiration time and issuing SIGSTOP/SIGCONT signals to the dynamodump process to suspend until the new credentials are written and resume, but no luck.

Example output from a request that failed due to an expired token:
```
[ec2-user@xxx ~]$ dynamodump --mode backup --srcTable mybigtable
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:root:Found 1 table(s) in DynamoDB host to backup: mybigtable
INFO:root:Starting backup for mybigtable..
INFO:root:Dumping table schema for mybigtable
INFO:root:Dumping table items for mybigtable

### some time later ###

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/dynamodump/dynamodump.py", line 729, in do_backup
    scanned_table = dynamo.scan(
  File "/home/ec2-user/.local/lib/python3.9/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the Scan operation: The security token included in the request is expired
```

**Comment by rorybakerfmr** [comment]
Hello, after researching this further, I no longer think this would be the preferred approach. Other users have requested the ability to reload fresh credentials from the shared credential file in boto3 and the other SDKs:
https://github.com/boto/botocore/issues/2450
https://github.com/boto/botocore/issues/704
https://github.com/aws/aws-sdk/issues/107

Instead, following the advice of @reegnz in the linked aws-sdk issue, we can specify a credential provider in our local machine's AWS profile. The general process is:

In `~/.aws/config`, set the following profile configuration (feel free to use a profile other than default):
```
[default]
credential_process = /path/to/my/loginscript.sh
```

According to https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html your credential provider must print a JSON object with the credentials to STDOUT. Our internal tool writes the credentials directly to the shared `~/.aws/credentials` file and also prints a generic success message to STDOUT, so we suppress that. Additionally note that your login script will likely need its own credentials to interact with your identity provider or other authentication mechanism, so I have omitted that for security reasons. (If you want the credential_process helper to read an environment variable for this, you can add it to your environment before running `dynamodump` or any other AWS command, i.e. `export MY_SECRET=...`) We also use the AWS CLI to interact with the shared credentials file rather than trying to parse it ourselves.

`loginscript.sh`
```bash
#!/bin/bash

# our tool uses the 'loginloop' profile as a temp placeholder. Note that 
# if this profile does not yet exist then the AWS CLI will print a message to STDERR,
# but credential_process only looks at STDOUT so no need to suppress the error
expiry_time=$(aws configure get expiry_time --profile loginloop)

# since our tool uses the shared credential file anyway, we use the loginloop profile
# as a credential cache so that we aren't requesting a new token on every invocation,
# only if the token is expired or not set
if [ -z "$expiry_time" ] || [ $(date -d "$expiry_time" +%s) -lt $(date +%s) ]; then
    # redirecting STDOUT to /dev/null so only errors are printed
    customlogintool --profile loginloop --role role-to-assume > /dev/null
fi

# Get the credentials from the `~/.aws/credentials` file under the `loginloop` profile
aws_creds=$(aws configure get aws_access_key_id --profile loginloop)
aws_secret=$(aws configure get aws_secret_access_key --profile loginloop)
aws_session=$(aws configure get aws_session_token --profile loginloop)
aws_expiry=$(aws configure get expiry_time --profile loginloop)

# write the JSON output to STDOUT
cat <<EOF
{
  "Version": 1,
  "AccessKeyId": "${aws_creds}",
  "SecretAccessKey": "${aws_secret}",
  "SessionToken": "${aws_session}",
  "Expiration": "${aws_expiry}"
}
EOF
```
